# Generated by Django 2.0.7 on 2018-09-29 10:30

import civilized_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilized_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsProvied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100)),
                ('job_file_name', models.FileField(upload_to=civilized_app.models.upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='file_name',
            field=models.FileField(upload_to=civilized_app.models.upload_path),
        ),
    ]
