# Generated by Django 2.0.7 on 2018-09-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={},
        ),
    ]
