# Generated by Django 2.0.7 on 2018-09-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_auto_20180908_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='subdescription',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
